# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9068cf8200dc7a986a7fe4d361fa5948"
name = "murtaza"
handle = "murtaza"
application_url = "https://dryer-beverages-frame-toward.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "conversion-king-x.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,read_themes,write_orders,write_products"

[auth]
redirect_urls = [
  "https://dryer-beverages-frame-toward.trycloudflare.com/auth/callback",
  "https://dryer-beverages-frame-toward.trycloudflare.com/auth/shopify/callback",
  "https://dryer-beverages-frame-toward.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-07"

[pos]
embedded = false
