# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9068cf8200dc7a986a7fe4d361fa5948"
name = "murtaza"
handle = "murtaza"
application_url = "https://fleet-potentially-significantly-scanners.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,read_themes,write_orders,write_products"

[auth]
redirect_urls = ["https://fleet-potentially-significantly-scanners.trycloudflare.com/auth/callback", "https://fleet-potentially-significantly-scanners.trycloudflare.com/auth/shopify/callback", "https://fleet-potentially-significantly-scanners.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
